### ISSUE TITLE
Python 3.8 + web terminal error

### ISSUE THREAD

**Issue by hoopty** [boatbod/op25#116]
When using Ubuntu 21.04 with gnuradio 3.8, get the following error when using the web terminal with `-l http:0.0.0.0:8080` argument, otherwise it works. 

Output:
```/opt/op25/op25/gr-op25_repeater/apps #./rx.py --nocrypt --args "rtl" --gains 'lna:47' -S 960000 -q -1 -d 0 -2 -V -T trunk.tsv -w -l http:0.0.0.0:8080
Using Python /usr/bin/python3
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.2.0
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
gain: name: LNA range: start 0 stop 0 step 0
setting gain lna to 47
supported sample rates 250000-2560000 step 24000
[R82XX] PLL not locked!
Using two-stage decimator for speed=960000, decim=10/4 if1=96000 if2=24000
op25_audio::open_socket(): enabled udp host(127.0.0.1), wireshark(23456), audio(23456)
p25_frame_assembler_impl: do_imbe[1], do_output[0], do_audio_output[1], do_phase2_tdma[1], do_nocrypt[1]
08/05/21 03:00:57.032399 Reading blacklist file
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/waitress/compat.py", line 119, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/op25/op25/gr-op25_repeater/apps/./rx.py", line 1068, in <module>
    rx = rx_main()
  File "/opt/op25/op25/gr-op25_repeater/apps/./rx.py", line 975, in __init__
    self.tb = p25_rx_block(self.options)
  File "/opt/op25/op25/gr-op25_repeater/apps/./rx.py", line 251, in __init__
    self.terminal = op25_terminal(self.input_q, self.output_q, self.options.terminal_type)
  File "/opt/op25/op25/gr-op25_repeater/apps/terminal.py", line 585, in op25_terminal
    return http_terminal(input_q, output_q, terminal_type.replace('http:', ''))
  File "/opt/op25/op25/gr-op25_repeater/apps/terminal.py", line 511, in __init__
    from http_server import http_server
  File "/opt/op25/op25/gr-op25_repeater/apps/http_server.py", line 30, in <module>
    from waitress.server import create_server
  File "/usr/lib/python3/dist-packages/waitress/__init__.py", line 1, in <module>
    from waitress.server import create_server
  File "/usr/lib/python3/dist-packages/waitress/server.py", line 20, in <module>
    from waitress import trigger
  File "/usr/lib/python3/dist-packages/waitress/trigger.py", line 20, in <module>
    from . import wasyncore
  File "/usr/lib/python3/dist-packages/waitress/wasyncore.py", line 54, in <module>
    from . import compat
  File "/usr/lib/python3/dist-packages/waitress/compat.py", line 121, in <module>
    from http import client as httplib
ImportError: bad magic number in 'http': b'\x03\xf3\r\n'```

**Comment by NebraskaCoder** [comment]
Try doing a pip3 install httplib
