### ISSUE TITLE
New VM cannot get running

### ISSUE THREAD

**Issue by Davidi74** [boatbod/op25#132]
Hi

Frustrated after so many weeks!! of trying to get OP25 running.

Fresh install of Ubuntu 16,18,20

Tried running BladeRF and RTL and both detect, but crash RX.ry

Why is there not a simple method of installation that actually works? I even saw someone offering $100 for a working VM and now I see why.

Below is a sample of SOME of the errors from Ubuntu 16.04

 setting gain LNA to 47
Using Volk machine: avx2_64_mmx_orc
Traceback (most recent call last):
  File "./rx.py", line 1074, in <module>
    rx = rx_main()
  File "./rx.py", line 980, in __init__
    self.tb = p25_rx_block(self.options)
  File "./rx.py", line 241, in __init__
    self.open_usrp()
  File "./rx.py", line 893, in open_usrp
    self.__set_rx_from_osmosdr()
  File "./rx.py", line 822, in __set_rx_from_osmosdr
    self.__build_graph(self.src, capture_rate)
  File "./rx.py", line 326, in __build_graph
    symbol_rate = self.symbol_rate)
  File "/home/user/op25/op25/gr-op25_repeater/apps/p25_demodulator.py", line 324, in __init__
    self.if1 = input_rate / self.decim
ZeroDivisionError: float division by zero

**Comment by boatbod** [comment]
You provided very little info to help out here.  Are the errors the same with the BladeRF and RTL?
Let's start with the RTL since that's what I'm most familiar with.  Please post full command line and the full stderr.2 log when it crashes.
