### ISSUE TITLE
rx.py no attribute 'open_file'

### ISSUE THREAD

**Issue by lilrags16** [boatbod/op25#151]
`[somehostname]~/op25/op25/gr-op25_repeater/apps$ python3 rx.py -i p25.out                                                                                                                                                              Traceback (most recent call last):
  File "rx.py", line 1075, in <module>
    rx = rx_main()
  File "rx.py", line 981, in __init__
    self.tb = p25_rx_block(self.options)
  File "rx.py", line 239, in __init__
    self.open_file(options.input)
  File "/usr/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 93, in                                                                                                                                                              __getattr__
    return getattr(self._impl, name)
AttributeError: 'top_block_sptr' object has no attribute 'open_file'
`

gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0

**Comment by boatbod** [comment]
Looks like a bug.  Not sure anyone other than you has tried to use the -i option for a long while!  What does your p25.out file contain?
