### ISSUE TITLE
-L (x) flag throws traceback & 44 byte file written to log, program hang

### ISSUE THREAD

**Issue by christhephish** [boatbod/op25#32]
attempting to log to disk via '-L (x)' causes .rx.py hang and traceback.  timer continues to increment 'last seen' time, however remainder of terminal.py does NOT update.

`Allocating 15 zero-copy buffers
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./rx.py", line 842, in run
    self.callback(msg)
  File "/home/christopher/op25/op25/gr-op25_repeater/apps/trunking.py", line 1068, in process_qmsg
    self.logging_scheduler(curr_time)
  File "/home/christopher/op25/op25/gr-op25_repeater/apps/trunking.py", line 1112, in logging_scheduler
    diff = abs(tsys.center_frequency - frequency)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'long'

main: exception occurred
main: exception:
Traceback (most recent call last):
  File "./rx.py", line 863, in run
    time.sleep(1)
KeyboardInterrupt
`

removing -L (x) from command line runs program as normal.

**Comment by boatbod** [comment]
-L logfile workers is largely untested and unsupported code.  Feel free to debug and submit a pull request and I'll integrate it.
