### ISSUE TITLE
New build, ImportError: No module named lfsr/op25-c4fm-mod (op25-c4fm-mod 404)

### ISSUE THREAD

**Issue by hayden-t** [boatbod/op25#67]
Traceback (most recent call last):
  File "/home/pi/op25/op25/gr-op25_repeater/apps/rx.py", line 57, in <module>
    import trunking
  File "/home/pi/op25/op25/gr-op25_repeater/apps/trunking.py", line 28, in <module>
    import lfsr
ImportError: No module named lfsr

seems it its not installed by install

also op25-c4fm-mod missing and pip reports 404

**Comment by hayden-t** [comment]
i needed to switch directories to apps folder first
